### ISSUE TITLE
reopen app throw an exception

### ISSUE THREAD

**Issue by koo9** [Daniel-Krzyczkowski/XamarinForms#3]
trace it to the call on App.cs constructor where it call SimpleIoc.Default.Register<INavigationService>(() => navigationService); since the navigation service is already registered on the first startup.  not sure what's the property way to fix this.

**Comment by Daniel-Krzyczkowski** [comment]
Thank you, I will try to check whats wrong and how to solve it.

**Comment by Daniel-Krzyczkowski** [comment]
koo9 Please tell me on which platform you have this exception? I cannot repro this bug.

**Comment by koo9** [comment]
hi Daniel,

it's on android. steps to reproduce the behavior.

1 start the app
2 tap navigate
3 tap physical back button until the app close
4 start the app again.  should see the error message.





Sent from my Samsung device


-------- Original message --------

**Comment by koo9** [comment]
i added a check on the app constructor to check if the navigation service is already registered with the ioc container,  then i won't register it again but then need to modify Inavigationservice to expose the initialize methods etc.



Sent from my Samsung device


-------- Original message --------

**Comment by Daniel-Krzyczkowski** [comment]
Thank you Kevin,


I tried different approaches but issue remains.

I created question on Stackoverflow - maybe someone faceb similar.


http://stackoverflow.com/questions/42337144/mvvm-light-there-is-already-a-factory-registered-for-inavigationservice



Daniel

________________________________

**Comment by koo9** [comment]
hi Daniel,

i tried skipping the registration if it is already registered. seems working for me.

Think when baking out with the back button,  the app go to sleep. so the *app domain* some how remained loaded. when the user open the app again,  the os will call resumed after instantiating a new instance but at the point the static instance of the ioc is still there. that's why we are getting the error.





Sent from my Samsung device


-------- Original message --------

**Comment by Daniel-Krzyczkowski** [comment]
Hi Kevin,


Thanks, I already tried different approaches:

1. Unregister and then register NavigationService in IoC

2. Check whether NavigationService was already registered


But once I did it nav igation is not working (I am clicking navigate button and there is no action). This is really weird.

What is your code for that?


Daniel


________________________________

**Comment by koo9** [comment]
yes. no need to unregister the service.  just need to check if it is already registered before registering. i think unregistering the service will lose the state, because the root navigation page is gone after setting the new main page. if you setup the navigation again, it will work if you want to unregister the service but i don't think it's necessary.



Sent from my Samsung device


-------- Original message --------

**Comment by Daniel-Krzyczkowski** [comment]
I am doing this:


            if(!SimpleIoc.Default.IsRegistered<INavigationService>())
            SimpleIoc.Default.Register<INavigationService>(() => navigationService);



But after I get back to the app Navigation is not working. There is no error but I cannto navigate.


Daniel

________________________________

**Comment by koo9** [comment]
INavigationService navigationService;

InitializeComponent();

if (!SimpleIoc.Default.IsRegistered<INavigationService>())
{
// Setup navigation service:
navigationService = new NavigationService();
// Configure pages:
navigationService.Configure(AppPages.MainPage, typeof(MainPage));
//navService.Configure(AppPages.DetailsPage, typeof(DetailsPage));

// Register NavigationService in IoC container:
var service = navigationService;
SimpleIoc.Default.Register<INavigationService>(() => service);
}
else
{
navigationService = SimpleIoc.Default.GetInstance<INavigationService>();
}

var firstPage = new NavigationPage(new MainPage());
// Set Navigation page as default page for Navigation Service:
navigationService.Initialize(firstPage);
// You have to also set MainPage property for the app:
MainPage = firstPage;



and of course, need to expose the following methods in INavigationService

void Configure(AppPages pageKey, Type pageType);
void Initialize(NavigationPage page);


HTH

Kevin





________________________________

**Comment by Daniel-Krzyczkowski** [comment]
Hi Kevin,


Yes, now it is working correctly and I thing this is the best way to solve this problem.


Thank you

Daniel




--
Kind Regards / Pozdrawiam

Daniel Krzyczkowski

pl: +48 503 995 830 | www.mobileprogrammer.pl<http://www.mobileprogrammer.pl>

[1477338838639_Stopka.png]
________________________________
