### ISSUE TITLE
Starting to create and execute tests on VS2017

### ISSUE THREAD

**Issue by andresousajr** [Daniel-Krzyczkowski/XamarinForms#4]
Hi Daniel,

I sent you a tweet but i think this plataforma it easier to discuss my doubts.

I'm studiying automated test by VS2017 using Xamarin Test Cloud, and it's been hard to find materials that explains how to use it. I'm struggling to start studying.

I need to understand things from the very beggining. Your blog of the 'Wordpress' talks about the Xamarin Studio but this plataforma is no longer available.

Do you have any material more  detailed about it?

**Comment by Daniel-Krzyczkowski** [comment]
Hi Andre,

Thanks for reaching out. Please write to this e-mail and let me know how exactly I can help you: mobileprogrammer@hotmail.com
